#!/bin/bash
(ls -A1 | awk '{if ($1 == "." || $1 == "..") {dotdirs = dotdirs $1 ","} else if (substr($1, 1, 1) ~ /[0-9a-zA-Z]/) {non_dotdirs = non_dotdirs $1 ","}} END {print dotdirs non_dotdirs}') | tr -d '\n' && echo
